### ISSUE TITLE
AttributeError: 'NamerConfig' object has no attribute 'watch_dir' but the config does have a value

### ISSUE THREAD

**Issue by RileyMo5038** [ThePornDatabase/namer#100]
Afternoon, All,

Apologies if this one is blatently simple, I'm trying to get to grips with Python.

Just playing with the configuration and am getting a curious outcome:
>   _File "C:\Users\[USER PATH]\AppData\Roaming\Python\Python310\site-packages\namer\configuration.py", line 412, in to_dict
>     "watch_dir": str(self.watch_dir),
> AttributeError: 'NamerConfig' object has no attribute 'watch_dir'

Yet when I go to line 271 (the object it refers to) there is indeed a directory. I've tried as many formats as I can but the error remains the same. I've tried the following:
>    watch_dir: P:\Test
>    watch_dir: "P:\Test"
>    watch_dir: r"P:\Test"
>    watch_dir: rf"P:\Test"

Am I missing something insanely obvious?

Thanks guys.

**Comment by 4c0d3r** [comment]
watch_dir has to be under the [watchdog] section. The folder must exist, no quotes or other markers necessary.


Like so: https://github.com/ThePornDatabase/namer/blob/main/namer.cfg.sample#L167-L186

**Comment by 4c0d3r** [comment]
You'll get better support in the namer channel of tpdb discord for usage requests like this.
