### ISSUE TITLE
Movies not identified when split scene available

### ISSUE THREAD

**Issue by gebau00a** [ThePornDatabase/namer#110]
I'm trying to let some movies auto tag and fail, example [https://metadataapi.net/movies/dorcel-betrayal
](url)
Filename is Dorcel.2021-04-14.Betrayal.mp4 in line with the metadata.

Namer always checked the scene's url only, never switching to movie when checking with the verbose flag.
Changes to namer.cfg to the movie_data_prefered, adding dorcel, still starts namer with
`INFO Querying: https://api.metadataapi.net/scenes?parse=dorcel.2021-04-14.Betrayal&limit=25`

I checked the metadataapi code and tried to follow the movie boolean.
I understood __metadata_api_lookup is started with scene reference due to the Movies=False, switching to Movies afterwards with the not movies.

```
def __metadata_api_lookup(name_parts: FileNameParts, namer_config: NamerConfig) -> List[ComparisonResult]:
    movies = False
    if name_parts.site:
        if name_parts.site.strip().upper() in namer_config.movie_data_prefered:
            movies = True

    results = []
    results = __metadata_api_lookup_type(results, name_parts, namer_config, movies)
    if not results or not results[0].is_match():
        results = __metadata_api_lookup_type(results, name_parts, namer_config, not movies)

    return results
```

The challenge here is now that Dorcel Betrayal is also available as split scenes [https://metadataapi.net/scenes/dorcel-betrayal-english-scene-1](url)

Thus, metadataapi will never trigger the movie check, as the scene check returns a result already.

I don't know how to solve the issue directly, maybe adding an option into namer to start with Movie or Scene first.
Alternatively, changing the filename to include Movie so it triggers the function.
I also tried to rename the file to the id, but the scraping fails.

**Comment by 4c0d3r** [comment]
When I test:  '''python -m namer suggest -f "dorcel.2021-04-14.Betrayal.mp4" -v''' The movie is what matches, as the date forces this to only match the movie, not scenes.  I can tell because of where the metadata comes from, which will result in the "type" variable, usable in names, being set to "movie"

2022-10-23T19:38:20.873210-0700 INFO Requesting GET "https://api.metadataapi.net/movies/2253052"
Dorcel - 2021-04-14 - Betrayal.mp4

Did you remove date checks from the "Dorcel" studio?   That would likely make edge cases like this appear.

**Comment by 4c0d3r** [comment]
also ```python -m namer suggest -f "dorcel.2021-01-01.Betrayal.mp4" -v``` wont result in a match, forcing UI usage to select, which seems reasonable to me.

**Comment by gebau00a** [comment]
> also `python -m namer suggest -f "dorcel.2021-01-01.Betrayal.mp4" -v` wont result in a match, forcing UI usage to select, which seems reasonable to me.

What you mean with UI usage?
Never saw this as I run namer on a headless SBC

**Comment by gebau00a** [comment]
[dorcel.2021-04-14.Betrayal.mp4.log](https://github.com/ThePornDatabase/namer/files/9848626/dorcel.2021-04-14.Betrayal.mp4.log)
[namer.cfg.txt](https://github.com/ThePornDatabase/namer/files/9848628/namer.cfg.txt)

Attached both files, my .namer.cfg and the log from the run with dorcel.2021-04-14.Betrayal.mp4

**Comment by gebau00a** [comment]
> When I test: `python -m namer suggest -f "dorcel.2021-04-14.Betrayal.mp4" -v` The movie is what matches, as the date forces this to only match the movie, not scenes. I can tell because of where the metadata comes from, which will result in the "type" variable, usable in names, being set to "movie"
> 
> 2022-10-23T19:38:20.873210-0700 INFO Requesting GET "https://api.metadataapi.net/movies/2253052" Dorcel - 2021-04-14 - Betrayal.mp4
> 
> Did you remove date checks from the "Dorcel" studio? That would likely make edge cases like this appear.

Not that I'm aware of. I tried in between with the movie_data_prefered tag for Dorcel but removed it again before submitting the bug report

**Comment by 4c0d3r** [comment]
> [dorcel.2021-04-14.Betrayal.mp4.log](https://github.com/ThePornDatabase/namer/files/9848626/dorcel.2021-04-14.Betrayal.mp4.log) [namer.cfg.txt](https://github.com/ThePornDatabase/namer/files/9848628/namer.cfg.txt)
> 
> Attached both files, my .namer.cfg and the log from the run with dorcel.2021-04-14.Betrayal.mp4

You just leaked you're tpdb key, you should rotate it.

**Comment by 4c0d3r** [comment]
I've confirmed it will work and match that name.... are you on the latest version?   Look at the first few lines of output after restarting docker if you use that.

**Comment by gebau00a** [comment]
I think you could be right, I installed via pip, it pulled 1.5.17
I found the reason, as I run on python-3.11 already, pip cannot find a suitable variant
```
ERROR: Ignored the following versions that require a different python version: 1.6.0 Requires-Python >=3.8,<3.11; 1.6.1 Requires-Python >=3.8,<3.11; 1.6.2 Requires-Python >=3.8,<3.11; 1.6.3 Requires-Python >=3.8,<3.11; 1.6.4 Requires-Python >=3.8,<3.11; 1.6.5 Requires-Python >=3.8,<3.11; 1.6.6 Requires-Python >=3.8,<3.11; 1.6.7 Requires-Python >=3.8,<3.11; 1.6.8 Requires-Python >=3.8,<3.11; 1.6.9 Requires-Python >=3.8,<3.11; 1.7.0 Requires-Python >=3.8,<3.11; 1.7.1 Requires-Python >=3.8,<3.11; 1.7.10 Requires-Python >=3.8,<3.11; 1.7.11 Requires-Python >=3.8,<3.11; 1.7.12 Requires-Python >=3.8,<3.11; 1.7.13 Requires-Python >=3.8,<3.11; 1.7.14 Requires-Python >=3.8,<3.11; 1.7.15 Requires-Python >=3.8,<3.11; 1.7.2 Requires-Python >=3.8,<3.11; 1.7.3 Requires-Python >=3.8,<3.11; 1.7.4 Requires-Python >=3.8,<3.11; 1.7.5 Requires-Python >=3.8,<3.11; 1.7.8 Requires-Python >=3.8,<3.11; 1.7.9 Requires-Python >=3.8,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11; 1.8.2 Requires-Python >=3.8,<3.11; 1.8.3 Requires-Python >=3.8,<3.11; 1.8.4 Requires-Python >=3.8,<3.11; 1.8.5 Requires-Python >=3.8,<3.11; 1.8.6 Requires-Python >=3.8,<3.11; 1.9.0 Requires-Python >=3.8,<3.11; 1.9.1 Requires-Python >=3.8,<3.11; 1.9.2 Requires-Python >=3.8,<3.11; 1.9.3 Requires-Python >=3.8,<3.11; 1.9.4 Requires-Python >=3.8,<3.11; 1.9.5 Requires-Python >=3.8,<3.11; 1.9.6 Requires-Python >=3.8,<3.11; 1.9.7 Requires-Python >=3.8,<3.11
ERROR: Could not find a version that satisfies the requirement namer==1.9.7 (from versions: 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.19, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.5.13, 1.5.14, 1.5.15, 1.5.16, 1.5.17)
ERROR: No matching distribution found for namer==1.9.7
```

I will close this bug and open a new one, asking for upgrade to python-3.11
