### ISSUE TITLE
Need a Plex Compatibility option

### ISSUE THREAD

**Issue by Darklyter** [ThePornDatabase/namer#118]
Since Plex ignores 'Movie' items that have TV Show style filenames, it will skip over scenes that have S##:E## style titles.

Need an option to ignore that part of a scene title if it's in the metadata (Such as Nubiles)

Something along the lines of removal of r'[sS]\d{1,3}:?[eE]\d{1,3}'

**Comment by 4c0d3r** [comment]
Fixed with new option in [namer] section, plex_hack, that when set to true uses the regex above.
