### ISSUE TITLE
Namer auto-adding scenes to collections on TPDB

### ISSUE THREAD

**Issue by Gykes** [ThePornDatabase/namer#128]
Looking to have the possibility of Namer: 

- Automatically adding scenes being auto added to collections on TPDB

TPDB can do the management of what has been collected but namer adding it in would be cool. 

Thanks

**Comment by insickin** [comment]
I'd like this possibility too!

**Comment by 4c0d3r** [comment]
@DirtyRacer1337 @ChalupaBatman69, in order to get this done the collection api needs an update, right now I can get the whole collection, and toggle a value, but namer shouldn't get the collection just to see if a item is in the collection before calling the toggle, thoughts?

**Comment by DirtyRacer1337** [comment]
there is `is_collected` field

**Comment by 4c0d3r** [comment]
released in 1.11.0
