### ISSUE TITLE
Problems with NFO files

### ISSUE THREAD

**Issue by Darklyter** [ThePornDatabase/namer#141]
1) The image paths are static instead of relative
<background>/media/dest/BrownBunnies/BrownBunnies - 2023-01-05 - Fucking in the Rain-background.png</background>

2) Random performer image is used as Poster instead of the actual poster image
<poster>/media/dest/BrownBunnies/BrownBunnies - 2023-01-05 - Fucking in the RainSarai-Minx-image.png</poster>

3) No break or separator  between original filename and performer name in performer images
<image>/media/dest/BrownBunnies/BrownBunnies - 2023-01-05 - Fucking in the RainJonathan-Jordan-image.png</image>

4) theporndbid displays page path instead of id.  Should be split into theporndbid with id only, and theporndburl with full url instead
<theporndbid>scenes/2620378</theporndbid>

**Comment by Darklyter** [comment]
Actually, would be nice to have ID as the returned data['id'], which I believe is the uuid/StashID for the scene

**Comment by 4c0d3r** [comment]
Merged for 1.11.2 - releasing now.

The theporndbid is a bit of a hack given that IDs are not unique between movies/scenes - all others fixes in.   Close this and open a new item?    Torn on how to handle the ID - but dirty did just add an enumeration for types.
