### ISSUE TITLE
Adding Network/Parent as a folder structure option

### ISSUE THREAD

**Issue by Gykes** [ThePornDatabase/namer#148]
My current folder structure goes as:

Mofos/Bangbus/SceneFolder/scene.mp4

With Namer I can only do:

Bangbus/Scenefolder/scene.mp4

Parent information is stored on TPDB so would it be possible to add a {network}, {network_full} option for the file renaming? As of now I can only go to site level then have to manually move it into it's parent folder. Would be awesome if it could do it by it's self, thanks!

**Comment by Darklyter** [comment]
To piggyback, or possibly read an exported list from Stash?  Should be simple to connect up to the Stash database with DBrowser and export a csv of the relationships
