### ISSUE TITLE
Option to choose which images to be downloaded

### ISSUE THREAD

**Issue by 2IkHLHB** [ThePornDatabase/namer#163]
When making changes via namer.cfg, under the option "enabled_poster", we get an all-or-nothing situation. When set to true, in addition to download the poster image, namer also downloads a background inage and all performers for said scene / movie.

If possible, it would be great to add an option on namer.cfg so we can choose which images we want (example, only poster + background, and nothing else)

When using .nfo files, both Plex and Jellyfin are very good at getting the performers' images without having namer downloading them. This, plus the added feature would help on keeping the folders clean and organized.

Thanks in advance, good day.

**Comment by geek-baba** [comment]
+1
