### ISSUE TITLE
Round off the resolution of a scene

### ISSUE THREAD

**Issue by thedesi1** [ThePornDatabase/namer#171]
I have a file that got renamed as follows:
`French Maid to Hire 5 (2021) - NathanBlake - 2021-07-07 - 2158`

This should be rounded off to nearest right resolution

`French Maid to Hire 5 (2021) - NathanBlake - 2021-07-07 - 2160p`

**Comment by 4c0d3r** [comment]
Honestly I'm not entirely sure this should happen. 
1) there may be a true 2160 out there and some people might want to know
2) there are a lot of different resolutions in use for vr which is also a supported thing (better than movies at this point).
3) rounding would have to have us set a threshold arbitrarily, and know all the resolutions we'd be round to......

**Comment by thedesi1** [comment]
1 out of 500 files so this is not a big deal, I was not sure why this happened though.

**Comment by 4c0d3r** [comment]
resolution is read from the file.   the file's not really 2160p

**Comment by thedesi1** [comment]
This can be closed, I thought this was a bug and I didn't thought through the other scenarios that exists like VR etc. This broke the tpdb search and I was thinking they way *arr's handle the resolution i.e. the closest match, but as mentioned not a big issue.
