### ISSUE TITLE
FIles ignored in watch directory

### ISSUE THREAD

**Issue by chadmorris2018** [ThePornDatabase/namer#184]
The majority of files placed in my watch directory are processed fine but I also am seeing about 10% of files completely ignored.  They are not moving to failed.  These all have mp4 extensions.  I have tried renaming the files to the same name as a working file and nothing.  Restarted and reinstalled namer with no success.  Any suggestions?  These do not even move to failed.

**Comment by DirtyRacer1337** [comment]
look it this settings

min_file_size : https://github.com/ThePornDatabase/namer/blob/main/namer/namer.cfg.default#L61
target_extensions : https://github.com/ThePornDatabase/namer/blob/main/namer/namer.cfg.default#L71

**Comment by chadmorris2018** [comment]
Thanks - missed that setting
