### ISSUE TITLE
Error installing namer on Windows 10

### ISSUE THREAD

**Issue by AiWABR** [ThePornDatabase/namer#188]
It is giving this error when installing the namer in Windows 10, do you know how to solve it? thanks for the work

C:\Windows\system32>pip install namer
Collecting namer
  Using cached namer-1.13.2-py3-none-any.whl (38.0 MB)
Collecting ConfigUpdater<4.0.0,>=3.1.1
  Using cached ConfigUpdater-3.1.1-py2.py3-none-any.whl (34 kB)
Collecting Flask-Compress<2.0,>=1.12
  Using cached Flask_Compress-1.13-py3-none-any.whl (7.9 kB)
Collecting Pillow<10.0.0,>=9.1.1
  Using cached Pillow-9.4.0-cp311-cp311-win_amd64.whl (2.5 MB)
Collecting Unidecode<2.0.0,>=1.3.4
  Using cached Unidecode-1.3.6-py3-none-any.whl (235 kB)
Collecting ffmpeg-python<0.3.0,>=0.2.0
  Using cached ffmpeg_python-0.2.0-py3-none-any.whl (25 kB)
Collecting flask<3.0.0,>=2.2.0
  Using cached Flask-2.2.3-py3-none-any.whl (101 kB)
Collecting imagehash<5.0.0,>=4.3.1
  Using cached ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
Collecting jinja2<4.0.0,>=3.1.2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting jsonpickle<4.0.0,>=3.0.1
  Using cached jsonpickle-3.0.1-py2.py3-none-any.whl (40 kB)
Collecting loguru<0.7.0,>=0.6.0
  Using cached loguru-0.6.0-py3-none-any.whl (58 kB)
Collecting mutagen<2.0.0,>=1.45.1
  Using cached mutagen-1.46.0-py3-none-any.whl (193 kB)
Collecting oshash<0.2.0,>=0.1.1
  Using cached oshash-0.1.1.tar.gz (3.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\__init__.py", line 268, in <module>
          monkey.patch_all()
        File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\monkey.py", line 97, in patch_all
          patch_for_msvc_specialized_compiler()
        File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\monkey.py", line 157, in patch_for_msvc_specialized_compiler
          patch_func(*msvc14('_get_vc_env'))
                      ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\monkey.py", line 147, in patch_params
          mod = import_module(mod_name)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 20, in <module>
          import unittest.mock as mock
      ValueError: source code string cannot contain null bytes
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by 4c0d3r** [comment]
I suspect you have a full disk or similar issue.   Installs are tested in windows on every build in ci.

**Comment by AiWABR** [comment]
I have 169 GB free on my SSD, I don't think it's due to lack of space

**Comment by 4c0d3r** [comment]
Well recommend you visit the discord to help debug your particular issue, as you can see windows is tested here:  https://github.com/ThePornDatabase/namer/actions/runs/4254266647/jobs/7401389516, this is using windows server 10.

**Comment by AiWABR** [comment]
Thanks for the answers, I solved the problem by reinstalling python, I'm already using it. Thank you very much
