### ISSUE TITLE
Posters No longer Contain Site Overlays

### ISSUE THREAD

**Issue by chadmorris2018** [ThePornDatabase/namer#192]
Over the past week, I have noticed that posters retrieved via namer no longer contain an overlay of the site logo/name.  Previously, namer would retrieve a poster that was in portrait layout with logo overlaid.  Now, it just retrieves the same poster as the background which is in landscape.  Has something changed with the PornDB site?

**Comment by 4c0d3r** [comment]
all porndb issue, folks are aware.
