### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Dagdandris** [ThePornDatabase/namer#194]
I added several files to the watch folder of Namer. The files failed to find a match automatically so they went to the failed folder. I went into the web GUI and manually matched 4 files. The 4 files were moved to the working folder and got stuck for around 5 minutes. After 5 minutes 3 of the 4 files were moved to the destination folder. One file remained in the working folder and got stuck for another 10 minutes until I was forced to close Namer. While this was going on my ram usage continued to steadily rise and my HDD was maxed out at 100%. When I closed Namer it was using approximately 16GB of ram and nearly had my computers 32GB Of ram maxed out. The second I closed our Namer, my ram utilization went from 28.5GB to 12.7GB. Here is a copy of the command prompt prior to me closing Namer.
![image](https://github.com/ThePornDatabase/namer/assets/84608870/132916d1-f0e6-44f2-b214-bed4749c050b)
![image](https://github.com/ThePornDatabase/namer/assets/84608870/53b3e434-d4e0-4822-8107-66d589065cd7)

[message.txt](https://github.com/ThePornDatabase/namer/files/11503949/message.txt)
5262/1108589413899972689/image.png)

**Comment by 4c0d3r** [comment]
If you have very large files, and are using mp4 embedding - it can take a large amount or processing/resources to embed the metadata in files.    part of this is likely cached filesystem content.    most users haven't reported this as an issue and have namer running for months, if you have something more exact - or hints based on your setup/usage pattern there might be something we can recommend you do.    also generating phash is intensive as well.    regardless this isn't something that can be addressed with the info provided, nor is it certain this isn't normal behavior on a very large mp4 - more over I've been running namer in a linux docker env with an old i3 and 16 gigs of ram with 20+ other containers, so there's something else going on here.   Maybe you're running the container in a vm or something else that chews up resources - where you should instead prefer the python pip?
