### ISSUE TITLE
mp4 files getting corrupted by ffmpeg?

### ISSUE THREAD

**Issue by DSew20** [ThePornDatabase/namer#197]
Further to earlier post re files not getting processed it appears all the files that were picked-up from watch_dir processed and moved and moved to failed_dir or dest_dir have somehow got corrupted.

The filenames in failed_dir are the same as original, the files open in VLC but can't be played.  Upon scanning with ffmpeg on Windows, I get 100's of errors as below.  The original file does not get errors, so somewhere namer has done something to the files.  There are many files that seem to be corrupted.  Any idea how to fix them?

```
missing picture in access unit with size 68
Invalid NAL unit size (0 > 64).
```

**Comment by 4c0d3r** [comment]
mp4 can have metadata embedded.    The feature uses a prebuilt version of ffmpeg.    Chances are you had some files that were not mp4 with the wrong extension, or you have network mounts whose drivers aren't playing nice with python/ffmpeg.

Also you should seek support in the tpdb discord where more people will be around to point you in the right direction.
