### ISSUE TITLE
Python 3.12 compability

### ISSUE THREAD

**Issue by gebau00a** [ThePornDatabase/namer#222]
Namer requires Python 3.11, with pyproject.toml explicitly asking for a version below 3.12.
Is this intended due to changes in Python 3.12 or it wasn't tested so far only?
What is needed despite the change in pyproject.toml to update Namer for Python 3.12?

**Comment by DirtyRacer1337** [comment]
When [poetry](https://github.com/python-poetry/poetry) would be available for 3.12, then I will do it
