### ISSUE TITLE
Web UI CSS for Failed tab fixed width too large for small screens.

### ISSUE THREAD

**Issue by sekondshand** [ThePornDatabase/namer#223]
For some reason, the CSS container that holds the Failed table is locked to `width: 2095px`, which goes off the side of my browser window. I looks like it's generated based on the font size (https://github.com/ThePornDatabase/namer/blob/main/src/templates/components/card.html#L6)?? 

`<table id="failed" class="table table-sm text-start align-middle dataTable no-footer" aria-describedby="failed_info" style="width: 2095px;">`

I'm using Firefox with the default fonts on an M1 Mac Air.

**Comment by DirtyRacer1337** [comment]
There is no code that will add that style to table, I can't reproduce that

**Comment by DirtyRacer1337** [comment]
Just try click refresh button, it's probably related with [DataTables](https://datatables.net/)
