### ISSUE TITLE
Where should the .namer.cfg file be stored on macOS?

### ISSUE THREAD

**Issue by kimiincn** [ThePornDatabase/namer#240]
<img width="1093" alt="ques" src="https://github.com/ThePornDatabase/namer/assets/87119726/8f6fd533-173b-4705-aedd-0966016f0333">

In the installation boot I only saw where it should be stored in Windows, where should it be stored in macOS?

**Comment by DirtyRacer1337** [comment]
probably https://www.google.com/search?q=mac+home+directory
