### ISSUE TITLE
I keep getting this error: requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by jobu59749** [ThePornDatabase/namer#241]
I keep getting this error message.  I haven't done anything to change the coding or anything.  Just fired it up and started uploading my files.  Is there a bigger issue going on or can someone tell me if there is just a back-end update happening and that's why it's having a connection problem?

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.metadataapi.net', port=443): Max retries exceeded with url: /movies?parse=bellesaplusleighraven29.&limit=25 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002D8228091D0>: Failed to resolve 'api.metadataapi.net' ([Errno 11001] getaddrinfo failed)"))

**Comment by jobu59749** [comment]
Nevermind...I just went to thepornDB site and saw the announcement that it is shutdown

**Comment by DirtyRacer1337** [comment]
We working on getting it back, keep eye on [Discord](https://discord.gg/CvmFRAAw)
