### ISSUE TITLE
Optional flag to not rename the file

### ISSUE THREAD

**Issue by stronk-throwaway** [ThePornDatabase/namer#257]
I'm trying to work namer in with my Whisparr flow for downloading scenes and it's painful. Namer does a great job on its own once videos are downloaded - although some videos require manual matching.

The problem is that Whisparr doesn't see the video name that it expects and it subsequently tries downloading a different release.

Is there a way to have namer tag the file and/or create the nfo, but not actually rename the file itself (or move the file to a new folder preserving the original name)? That way as far as Whisparr is concerned the file just took a longer time to download and it can handle the organization/renaming itself.

**Comment by DirtyRacer1337** [comment]
namer made for renaming files, so no
