### ISSUE TITLE
Items not recognized in my watch folder 

### ISSUE THREAD

**Issue by Cromulent01** [ThePornDatabase/namer#261]
I have many items that are mp4 or mkv, the file is playable , correctly labeled per porndb Namer never recognizes them they never show up in the command prompt its almost like they don't exist. I have tried removing them relabeling them and putting them back in but they never get moved to the working folder. This has happened with roughly 1/4 of my files. Not failed just never recognized.

**Comment by DirtyRacer1337** [comment]
check this, https://github.com/ThePornDatabase/namer/blob/main/namer/namer.cfg.default#L65

**Comment by Cromulent01** [comment]
Thank you this was the solution. I changed it to 3.
