### ISSUE TITLE
Is there a hang sometimes on running a query?

### ISSUE THREAD

**Issue by PAHelper2** [ThePornDatabase/namer#4]
Hi,

I've been using the latest docker container, to process a big backlog of unmatched scenes.  Generally, things work great.  However, sometimes I notice from the docker logs, that namer appears stuck, with the last log line being a query to TPDB.

Is there a timeout on this query?  I resolve this by restarting the container.

Thanks.

**Comment by 4c0d3r** [comment]
No timeout, but perhaps a memory leak in rapid fuzz or elsewhere, can you estimate the number of processed files before a hang?

**Comment by PAHelper2** [comment]
Good question.  I'll try to reproduce.

**Comment by 4c0d3r** [comment]
No longer getting feedback on sporadic failures, so closing.
