### ISSUE TITLE
Option to turn off log files for failed?

### ISSUE THREAD

**Issue by dsrtusr88** [ThePornDatabase/namer#52]
I'd like to have the option to toggle this.  For large libraries these can add up.

**Comment by 4c0d3r** [comment]
for just the failed dir?   or in the dest dirs?

**Comment by dsrtusr88** [comment]
for the failed dir

**Comment by 4c0d3r** [comment]
Is this for when the files first get written to the failed dir, or after they are matched and moved to the dest dir?   There's already an option to not preserve log files when moving to the dest dir - have you turned that on?   The failed dir .log files can help inform the UI (you can click on the log and see what almost matched).    They should also be removed when files are moved to the dest dir.   Is any of the above not the case for you?    If so how please describe the videos leaving log files behind in the failed dir?   I'm inclined to leave the logs in the failed dir until there's a better way to help indicate what users might want to search for in the UI.   Thoughts?   I know it's not what you asked but namer is already too configurable to test effectively, I need to start removing config options soon.

**Comment by dsrtusr88** [comment]
yea, i'm talking about logs in the failed directory.  i've got 20k+ files that hang in there all with log files attached to them

**Comment by 4c0d3r** [comment]
Don't want to tell how to use the software but those 20k+ files that wont match are attempted every night against tpdb, so you are hitting the server with a pretty high load that sounds like it has little chance of matching?    Seems like an abuse of the service to me.   You should likely have a reasonable expectation of the files matching when leaving them in the failed dir.   This is meant for the times when the metadata in tpdb has lagged by a few days (scraping often gets overloaded to push data to tpdb).   Or to indicate a rescrape is needed if videos were missed.   I would suggest working through chunks of the files at a time.   Request in discord when metadata doesn't exist to scrape more sites if they are unmatchable sites, or write a small shell script to get the files named in a structure namer can use to finally make a match.

**Comment by dsrtusr88** [comment]
@DirtyRacer1337 from what I'm seeing in Namer logs, it's reasonably parsing out files and in a lot of cases just not finding the site in tpdb to match against.  Can these be used to suggest/vote new sites to add or better terms to compare against to increase chances of matching?

**Comment by DirtyRacer1337** [comment]
> @DirtyRacer1337 from what I'm seeing in Namer logs, it's reasonably parsing out files and in a lot of cases just not finding the site in tpdb to match against. Can these be used to suggest/vote new sites to add or better terms to compare against to increase chances of matching?

For adding site url would be needed anyway, better just send request to tpdb discord
