### ISSUE TITLE
poster.jpg and background.jpg being removed

### ISSUE THREAD

**Issue by josst10** [ThePornDatabase/namer#64]
I have been playing with namer, watchdog, and every other fun solution out there over the last few years. This thing is amazing!!! There is one thing I would love to see, however.

I manage my own posters and backgrounds. In the scenes folder, there will be 3 files -- poster.jpg, background.jpg, and the video file itself. I would love to be able to put those folders through namer and have those pictures travel along with the file. 

Again, thanks so much!!!

**Comment by 4c0d3r** [comment]
There should be a flag for that, "remove other files" if this is set to false, and if your files are in a directory, none of those files should be removed.

**Comment by josst10** [comment]
[namer]

# token to access porndb.
# sign up here: https://metadataapi.net/register
porndb_token = 5burYSSBqiKOyFDFDWZpsQzAd8tP5sdfdsfsdfhOkAj7OWSN8gTwY

# How to write output file name.  When namer.py is run this is applied in place 
# (next to the file to be processed).
# If you are running watchdog see new_relative_path_name in the watchdog section.
#
# Supports stand python 3 formatting, as well as:
# * a prefix:
# {site: 1p} - in this case put one space in front of the 'site', so ' Vixen'
# * a suffix:
# {date:_1s} - in this case put one underscore after the 'date', so '2020-01-01_'
# * an infix:
# {date:_2i} - in this case put two underscore before and after the 'date', so '__2020-01-01__'
#
# Examples: 
# * {site} - {date} - {scene}.{ext}
# * {site}/{date}.{scene}.{ext}
#
# Missing values will be ignored.
#
# Allowed replacements:
#
# * 'date' - in the format of YYYY-MM-DD.
# * 'description' - too long, don't use in a name.
# * 'name' - the scene name
# * 'site' - the site name, BrazzersExxtra, AllHerLuv, Deeper, etc with spaces removed.
# * 'full_site' - the site name from porndb, unmodified, i.e: Brazzers Exxtra, All Her Luv, etc.
# * 'performers' - space seperated list of female performers
# * 'all_performers' - space seperated list of all performers
# * 'act' - an act, parsed from original file name, don't use.
# * 'ext' - original file's extension, you should keep this.
# * 'trans' - 'TS', or 'ts' if detected in original file name.
#
# This should not contain paths, as files will be processed in place when called on the command line from namer.  
inplace_name={site} - {date} - {name}.{ext}

# If a directory name is to be preferred over a file name.
# Directories are calculated by taking the first part of a relative path
# to the watch_dir location, or as input to namer via -d parameter.
prefer_dir_name_if_available = True

# minimum file size to process in MB, ignored if a file is to be processed
min_file_size = 300

# Should namer's comparison log be written next to successfully moved videos (it will always be added to the failed dir).
write_namer_log = True

# Comma separated list of extensions for namer to process (in order of preference in case multiple types exist in a target directory)
# Case insensitive, Only mp4 supports tagging.  
target_extensions = mp4,mkv,avi,mov,flv

# Should new and moved files have permissions and ownership set.
update_permissions_ownership = False

# Settings for new/moved files/dirs.
#set_dir_permissions = 777
#set_file_permissions = 777

# Setting uid and groupid for new and moved files.
# Use the id numbers, not names.  Defaults to process uid/gid in non windows systems.

#set_uid = 1001
#set_gid = 1000

# If you want the trailers downloaded set the value relative to the final location of the movie file here.
# Currently assumes directory per video, and doesn't work in vast majority of cases (cdns with caches busted,
# expired view tokens, etc.)
# Plex:      Trailers/trailer.{ext}, or extras/Trailer-trailer.{ext}
# Jellyfin:  trailer/trailer.{ext}
# Extensions are handled by the download's mime type.
# Leave empty to not download trailers.
trailer_location =

# Comma seperated list of sites whose date information in tpdb is known to be sketchy at best as the
# values are set to the scrape time, not the video release date.
sites_with_no_date_info =

# When guessing at matches namer can use performer names to attempt to match.   This can be costly in terms of cpu time.
# Plus who lists all the performers if over 6 on a scene's name?   You can increase this, but the cpu/runtime cost increases
# rapidly (combinatorial)
max_performer_names = 6

# Cache http requests
use_requests_cache = True

# Amount of minutes that http request would be in cache
requests_cache_expire_minutes = 10

[metadata]
# Currently metadata pulled from the porndb can be added to mp4 files or .nfo files.
# MP4 metadata will be read in fully by Plex, and Apple TV app, partially by Jellyfin (no artist support).
# Metadata includes, Title, Release Date, Scene Name, Artist, Source URL, XXX Movie rating.
# If a file is not an mp4 adding metadata at this time isn't supported.
# .nfo files are supported by a number of players, though some require plugins.

#  Write an nfo file next to the directory in an emby/jellyfin readable format
write_nfo = True

# Should metadata fetched from the porn db be written in to the metadata of the mp4.
enabled_tagging = False

# Should the poster fetched from the porn db be written in to the metadata of the mp4.
# This poster will be displayed in Plex, Jellyfin and Apple TV app.
# Controls downloading of images for .nfo and mp4 tagging.
enabled_poster = False

# These genres are noisey and not recommend for use.  If this is false a single default
# genre will be used.  These are called Tags on the porndb json response objects, genre's
# in plex/jellyfin - and could be added as Tags to jellyfin.  Unfortunately jellyfin doesn't
# support searching tags, so tpdb jellyfin plugin writes tags to genres, this flag will
# mirror that behavior for mp4s and .nfo files.   It does appear jellyfin will get tag filtering 
# in the 10.8 release due to a few prs out there. 
enable_metadataapi_genres = False

# If genre's are not copied this is the default genre added to files.
# Default value is adult.
default_genre = Adult

# if language is set it will be used to select the default audio stream in an mp4 that has too many default stream
# to play correct in quicktime/apple tv.   If the language isn't found or is already the only default no action is
# taken, no streams (audio/video) are re-encoded.  See: https://iso639-3.sil.org/code_tables/639/data/
language = eng

[duplicates]

# If this is set to false duplicates will be discarded, and a rough selection criteria can be configured below
# to select the retained video
presever_duplicates = True

# If set to -1, no max resolution is set.   Others selecting 720, 1080, 2160, 4380, etc will limit retained videos
# to the desired resolution.   If a too large video is the only one available it will be retained.  Defautls to 4380
max_desired_resolutions = -1

# The codecs in order that you want to retain.   
# by default hevc is preferred to h264, which is preferred vs everything else.
desired_codec = hevc, h264


[watchdog]

# If the file path found by watcher matches this regex, it will not trigger processing.
ignored_dir_regex = .*_UNPACK_.*

# when processing a directory should other files be removed.
# to keep other files this must be false and new_relative_path_name must contain a directory split, "/"
del_other_files = False

# After a video has appeared in the watch dir, an extra number of seconds to wait to allow the 
# copying or unzipping of other files in to that directory.   Prevents leaving orphaned files in dirs with 
# with no movies of you have del_other_files set to True.
extra_sleep_time = 30

# Configured like inplace_name above, but with paths, and is relative to
# dest_dir, which is where completed files will be moved to. 
new_relative_path_name = {site}/{site} - {date} - {name}/{site} - {date} - {performers} - {name}.{ext}

# director where new downloads go.
watch_dir = /media/watch

# temporary directory where work is done.
# a log file shows attempted matches and match closeness.
work_dir = /media/work

# Should processing fail the file or directory is moved here.
# retries occur every 12 hours.   Files can be manually moved to watch-dir
# to force reprocessing.
failed_dir = /media/failed

# dir where finalized files get written.
dest_dir = /media/dest

# When to retry failed items, default is a random minute during the 3 am hour in your timezone.
#retry_time = 03:16

# Run webserver while running watchdog.
web = False

# port to run on
port = 6980

# target host
host = 0.0.0.0

# webroot (root url to place pages), useful for reverse proxies
web_root =

# Allow to delete files in web interface
allow_delete_files = False

# Errors may be raised by the program, and when they are loguru may be used to help explain them, showing 
# values in the stack trace, potentially including the porndb token, this setting should only be turned on
# if you are going to check an logs you share for your token.
diagnose_errors = False

**Comment by josst10** [comment]
Do you mean these flags?
- new_relative_path_name = {site}/{site} - {date} - {name}/{site} - {date} - {performers} - {name}.{ext}
- del_other_files = False

I have tried a bunch of times and had no success. I am able to write the .nfo and it makes it to the new destination. 

Thanks!

**Comment by 4c0d3r** [comment]
sound like you are using namer to write the .nfos which download the jpgs then replacing the ones you provide?

This sounds like an order of operations problem.

I would suggest using namer as part of whatever script you have writing the image files.  Namer can be installed as a pip and easily called to rename a single file and write the .nfos as output.

Namer can run command line and leave files in the directory after renaming them, or move them to the root of a directory if using directory names.

Have namer rename the movie in place, write the infos, the have your code copy files in and then finally move the whole thing to the final location.

Or you can put the files next to existing .jpgs and update them after namer has processed them and moved them to the dest dir.

There are too many cases like this that have already led to far to many configurations in namer.    And if others can't benefit from me adding this,I'm going to have to recommend you use one of the work arounds above.

**Comment by josst10** [comment]
I'm cool with a workaround, however, I cannot get them to move at all. There is no other script I am trying to use with it. I have a directory named '21 naturals' and in it, I have 10 files named like the following:

21Naturals - 2020-01-27 - Charlie Dean, Sybil

They have one jpg each for posters (poster.jpg) and background (background.jpg) in the folder. I am using docker on unraid. I copied the 'namer.cfg.sample' and changed minimal things to just get it up and running. 

This folder (21Naturals - 2020-01-27 - Charlie Dean, Sybil) will stay in the 'watch' directory with poster.jpg and background.jpg while in the 'dest' folder, it also has the same folder (21Naturals - 2020-01-27 - Charlie Dean, Sybil) except with the .mp4 file.

I can use the CLI as well; I just wanted to let you know that at least for me, the 'other files' are not moving with the video as I was expecting. 

Thanks again!

**Comment by 4c0d3r** [comment]
Alright that might be a bug.   Worth adding a test for.   _might_ get to it this weekend.   slammed right now.

**Comment by 4c0d3r** [comment]
also did you check file permissions.   if they were written by jellyfin, they usually have a restrictive permission for groups, so those files might not be editable

**Comment by josst10** [comment]
Through unraid I use a script that does the following: 

> The utility starts a background process that goes to each of your data disks and cache disks and selected user shares and changes file and directory ownership to nobody/users (i.e., uid/gid to 99/100), and sets permissions as follows:
> 
> For directories:
>   drwxrwxrwx
> 
> For read/write files:
>   -rw-rw-rw-
> 
> For readonly files:
>   -r--r--r--

I run it after I run a few files through the Namer docker container and don't get the output I want.  It gets me back to baseline and makes sure everything has the same ownership/permissions for when I try again.

I'll play around with the permissions and see if I can't figure anything out.

**Comment by 4c0d3r** [comment]
This was a bug, fixed here:   https://github.com/ThePornDatabase/namer/commit/44b2ee8ddbec4ca74a8bf39be91a39e646df2bec

**Comment by 4c0d3r** [comment]
Please test and close.

**Comment by josst10** [comment]
Lookin' great! Thanks.

**Comment by josst10** [comment]
I changed the new_relative_path_name={site}/{site} - {date} - {name}/{site} - {date} - {name}.{ext} and this was the result for the poster. 

(dir) 21FootArt
       /21FootArt - 2015-09-19 - Glorious Footjob
       /poster.jpg

The poster file is now in the main 21FootArt directory and not the glorious footjob directory. (BTW, I am fine with current functionality so don't prioritize this for me. I'm just following up so you know and offering to help.)

**Comment by 4c0d3r** [comment]
I see what I did wrong....   didn't test for these kinds of structures.   but good catch.

**Comment by 4c0d3r** [comment]
fix is building now, will be 1.7.1

**Comment by 4c0d3r** [comment]
released, please check it out again, and this time I expect the issue will stay closed :D

**Comment by josst10** [comment]
Beautiful! Looks great. I'll close out and if you need any testing again just send up the bat signal and I'll help out.
