### ISSUE TITLE
UUID no longer works in new filepath

### ISSUE THREAD

**Issue by thezak48** [ThePornDatabase/namer#72]
I have been using namer to put processed scenes in this format
new_relative_path_name={site}/{site} - {date} - {name} [tpdb-{uuid}]/{site} - {date} - {name}.{ext}

However I have only just noticed that it is no longer working and saying {uuid} is not a valid key. Have you dropped support for this? I see nothing is change logs that that is the case

**Comment by 4c0d3r** [comment]
Fixed, 1.7.8 release inbound.
