### ISSUE TITLE
Option to set frequency of failed job researches

### ISSUE THREAD

**Issue by dsrtusr88** [ThePornDatabase/namer#73]
Is there a way to set the frequency of failed job retries to something like weekly or monthly instead of daily?

**Comment by 4c0d3r** [comment]
Currently, no.   The daily pulls are a way to deal with tpdb lagging on some scrapes.   Often delayed by 1-3 days.   A cron tab might appeal to some, but I can't think of a use case for it.   Either tpdb scrapes sites, or it doesn't.    Scrape requests are either acted upon in under a week, or refused immediately for meaningful reasons.   Why keep the videos in the failed dir if they aren't covered by tpdb?

**Comment by dsrtusr88** [comment]
there's active work to build functionality for new sites, some of them eventually catch up and update

**Comment by 4c0d3r** [comment]
agreed, I follow the work that Darklyter and others are doing.    They tend to bang out scrapers pretty quickly.    I started a conversation in the discord to ask users what they think of the request.   Trying to keep the app simple as possible and not convinced this request would anyones work flow any simpler.    It seems you'd need some files to be daily for when scrapers lag (why the capability exists), and some to be monthly in hopes a site gets added?

**Comment by 4c0d3r** [comment]
closing for now until a concrete plan is suggested.
