### ISSUE TITLE
[FR] Add site abbreviation support

### ISSUE THREAD

**Issue by thezak48** [ThePornDatabase/namer#84]
Ether a setting in the config for site abbreviations i.e. (abbreviations=["abr":"A Bare Rump", ....]  )
or as a separate file for them

As discussed in discord https://discord.com/channels/957516730727563285/957516731654488091/1015037937206956155

**Comment by DirtyRacer1337** [comment]
Don't know what you discussed in discord (no access), but this should be enough

**Comment by 4c0d3r** [comment]
built on top of @DirtyRacer1337 additions to allow a user to override in config the standard set from the porndb.  added a test as well.   You'll need to update your config @thezak48, just use the sample config as an example.
