### ISSUE TITLE
Use original filename if automatically matched by watchdog

### ISSUE THREAD

**Issue by MikeLund** [ThePornDatabase/namer#97]
My desired usecase is using watchdog to automatically see which files the Plex Agent would otherwise fail to match on -- configuring watchdog to rename files ONLY if they required a manual match in the watchdog webui.

Two different cases: 
1. Adding a properly-named file `sitename.22.03.05.scenename.blahblah.1080p.mp4` to watch_dir gets **automatically** matched by watchdog successfully -> move it to dest_dir without changing anything. (This being my new requested functionality)
2. Adding file `not.in.correct.naming.format.etc.etc.mp4` doesn't get matched by watchdog -> I manually match it in webui -> it gets renamed using the format specified in `new_relative_path_name`. (This being the current/normal functionality)

Why?
- I prefer files being as "untouched" as possible for original consistency; if the filename works properly as-is for getting metadata, I don't want to change it. Consider as well in the (hopefully rare) case something gets matched incorrectly, it's troublesome when the original filename is gone.
- Most of my files are acquired from a private tracker automatically via RSS, and they often have a naming scheme where automatic detection with your Plex Agent works without problems. And so if I get a request in the future to reseed a specific filename, it's easier to automatically find that filename if it hasn't otherwise been modified.
- I don't use any of the enabled_* metadata options for the same reasons (and that it would change filehash for reseeding) -- I want to rely 100% on the Plex Agent to match the files that have been previously "accepted" via watchdog.

Thanks for the great work otherwise, I found this project earlier today and love the effort put into it :)

**Comment by 4c0d3r** [comment]
@Darklyter can we come up with a definition of what the plugins matching algo must be?   I would have to re-implement it in namer to complete this item.    Just seeing the algo spelled out and committed to in the plugins would be enough.

**Comment by neingeist** [comment]
With the proposed change in PR #264, this config:

```
new_relative_path_name={full_site} - {date} - {name:|truncate(100, False, "…", 0)}/{source_file_name}
```

would use the original filename, but use metadata for the directory name. (The `truncate` is not relevant here, it's just my full configuration.)
